version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
    # environment:
    #   - APP_ENV=development
    #   - DB_HOST=postgres
    #   - DB_PORT=5432
    #   - DB_USER=postgres
    #   - DB_PASSWORD=123
    #   - DB_NAME=affpilot_auth
    #   - JWT_SECRET=your-secret-key-here
    #   - JWT_EXPIRY=24h
    #   - SYSTEM_ADMIN_USERNAME=admin
    #   - SYSTEM_ADMIN_PASSWORD=adminpassword
    #   - SYSTEM_ADMIN_EMAIL=admin@example.com
    #   - PASSWORD_SALT=your-password-salt-here
    #   - PASSWORD_RESET_TTL=5m
    #   - EMAIL_VERIFICATION_URL=http://localhost:8080/api/v1/auth/verify
    #   - EMAIL_FROM=sagor.sarker0709@gmail.com
    #   - EMAIL_HOST=smtp.gmail.com
    #   - EMAIL_PORT=587
    #   - EMAIL_USERNAME=sagor.sarker0709@gmail.com
    #   - EMAIL_PASSWORD=xfsuriympbeyplln
    #   - EMAIL_SECURE=true
    #   - VERIFICATION_TOKEN_TTL=5m
    #   - LOG_LEVEL=debug
    #   - SERVER_PORT=8080
  
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=affpilot_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
